import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providors from "./providors";
import NavBar from "./components/NavBar";
import SidePanel from "./components/SidePanel";
import { Suspense } from "react";
import { Spinner } from "@nextui-org/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providors>
        <body className={inter.className}>
          <div className="grid grid-cols-iconContentGrid lg:grid-cols-contentGrid grid-rows-contentGrid h-svh">
            <SidePanel />
            <NavBar />
            <main className="overflow-auto p-10">
              <Suspense
                fallback={
                  <div className="flex w-full h-full items-center justify-center">
                    <Spinner
                      size="lg"
                      className="bg-default-100 p-1 rounded-md"
                      color="primary"
                    />
                  </div>
                }
              >
                {children}
              </Suspense>
            </main>
          </div>
        </body>
      </Providors>
    </html>
  );
}
